name: crypto_app
description: Cool crypto application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.3.10

  flutter_svg: ^2.0.10+1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/robotoMono/regular.ttf
        - asset: assets/fonts/robotoMono/regular_italic.ttf
          style: italic
        - asset: assets/fonts/robotoMono/medium.ttf
          weight: 500
        - asset: assets/fonts/robotoMono/bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/bold.ttf
          weight: 700
        - asset: assets/fonts/lato/bold_italic.ttf
          weight: 700
          style: italic

    - family: Parisienne
      fonts:
        - asset: assets/fonts/parisienne/regular.ttf

    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm_sans/regular.ttf
          weight: 400

    - family: Lufga
      fonts:
        - asset: assets/fonts/lufga/medium.ttf
          weight: 500
        - asset: assets/fonts/lufga/bold.ttf
          weight: 600
